version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_usuarios
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  ms-usuarios:
    image: ghcr.io/katalina-star/repogps-backend:latest
    environment:
      - NODE_OPTIONS=--max-old-space-size=256
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: ghcr.io/katalina-star/repogps-frontend:latest
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "5173:5173"
    depends_on:
      - ms-usuarios