events {}

http {
    server {
        listen 8045;

        # 1. RUTAS MANTENEDOR
        location /api/areas {
            proxy_pass http://ms-mantenedor:3001/api/areas;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/contratistas {
            proxy_pass http://ms-mantenedor:3001/api/contratistas;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/disciplinas {
            proxy_pass http://ms-mantenedor:3001/api/disciplinas;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. RUTA USUARIOS
        location /api/ {
            proxy_pass http://ms-usuarios:3000/api/;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. RUTA FRONTEND
        location / {
            proxy_pass http://frontend:5173/;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}